# Applications - launchers and app-specific bindings

# Set programs
$terminal = kitty
$fileManager = nautilus 
$browser = firefox

# Terminal bindings
unbind = $mainMod, RETURN
bindd = $mainMod, RETURN, ZSH, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)" -e zsh
bind = $mainMod, BACKSPACE,exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)" -e zsh
bind = $mainMod Alt, Return, exec, $terminal --class float_kitty

# File Manager
bind = $mainMod, E, exec, $fileManager

# Browser
bind = $mainMod SHIFT, RETURN, exec, $BROWSER
bind = $mainMod SHIFT, BACKSPACE, exec, $BROWSER

# App launcher
bind = $mainMod, Space, exec, $menu
bind = $mainMod SHIFT, W, exec, waypaper
