# Window groups

# Toggle groups
bindd = $mainMod, G, Toggle window grouping, togglegroup
bindd = $mainMod ALT, G, Move active window out of group, moveoutofgroup

# Join groups
bindd = $mainMod ALT, LEFT, Move window to group on left, moveintogroup, l
bindd = $mainMod ALT, RIGHT, Move window to group on right, moveintogroup, r
bindd = $mainMod ALT, UP, Move window to group on top, moveintogroup, u
bindd = $mainMod ALT, DOWN, Move window to group on bottom, moveintogroup, d

# Navigate a single set of grouped windows
bindd = $mainMod ALT, TAB, Next window in group, changegroupactive, f
bindd = $mainMod ALT SHIFT, TAB, Previous window in group, changegroupactive, b

# Window navigation for grouped windows
bindd = $mainMod CTRL, LEFT, Move grouped window focus left, changegroupactive, b
bindd = $mainMod CTRL, RIGHT, Move grouped window focus right, changegroupactive, f

# Scroll through a set of grouped windows with $mainMod + ALT + scroll
bindd = $mainMod ALT, mouse_down, Next window in group, changegroupactive, f
bindd = $mainMod ALT, mouse_up, Previous window in group, changegroupactive, b

# Activate window in a group by number
bindd = $mainMod ALT, code:10, Switch to group window 1, changegroupactive, 1
bindd = $mainMod ALT, code:11, Switch to group window 2, changegroupactive, 2
bindd = $mainMod ALT, code:12, Switch to group window 3, changegroupactive, 3
bindd = $mainMod ALT, code:13, Switch to group window 4, changegroupactive, 4
bindd = $mainMod ALT, code:14, Switch to group window 5, changegroupactive, 5