# Window navigation - move focus, resize, swap

# Move focus with mainMod + HJKL (vim motion)
unbind = $mainMod, J
bind = $mainMod, J, movefocus, d
unbind = $mainMod, L
bind = $mainMod, L, movefocus, r
unbind = $mainMod, H
bind = $mainMod, H, movefocus, l
unbind = $mainMod, K
bind = $mainMod, K, movefocus, u

# Move focus with mainMod + arrows
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Resize windows with mainMod + Ctrl + HJKL (vim motion)
unbind = $mainMod CTRL, H
unbind = $mainMod CTRL, L
unbind = $mainMod CTRL, J
unbind = $mainMod CTRL, K
bind = $mainMod CTRL, H, resizeactive, -10% 0
bind = $mainMod CTRL, L, resizeactive, 10% 0
bind = $mainMod CTRL, J, resizeactive, 0 -10%
bind = $mainMod CTRL, K, resizeactive, 0 10%

# Resize windows with mainMod + Ctrl + arrows
unbind = $mainMod CTRL, left
unbind = $mainMod CTRL, right
unbind = $mainMod CTRL, up
unbind = $mainMod CTRL, down
bind = $mainMod CTRL, left, resizeactive, -10% 0
bind = $mainMod CTRL, right, resizeactive, 10% 0
bind = $mainMod CTRL, up, resizeactive, 0 10%
bind = $mainMod CTRL, down, resizeactive, 0 -10%

# Swap windows with mainMod + Shift + HJKL (vim motion)
unbind = $mainMod SHIFT, H
unbind = $mainMod SHIFT, L
unbind = $mainMod SHIFT, J
unbind = $mainMod SHIFT, K
bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, J, swapwindow, d
bind = $mainMod SHIFT, K, swapwindow, u

# Swap windows with mainMod + Shift + arrows
unbind = $mainMod SHIFT, left
unbind = $mainMod SHIFT, right
unbind = $mainMod SHIFT, up
unbind = $mainMod SHIFT, down
bind = $mainMod SHIFT, left, swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, down, swapwindow, d
bind = $mainMod SHIFT, up, swapwindow, u