# Window management - tiling, floating, fullscreen, close

# Close windows
bindd = $mainMod, W, Close window, killactive,
bindd = CTRL ALT, DELETE, Close all windows, exec, omarchy-hyprland-window-close-all

# Control tiling
# bindd = $mainMod, J, Toggle window split, layoutmsg, togglesplit
# bindd = $mainMod, P, Pseudo window, pseudo, # dwindle
bindd = $mainMod, T, Toggle window floating/tiling, togglefloating,
bindd = $mainMod, F, Full screen, fullscreen, 0
bindd = $mainMod CTRL, F, Tiled full screen, fullscreenstate, 0 2
bindd = $mainMod ALT, F, Full width, fullscreen, 1
bindd = $mainMod, O, Pop window out (float & pin), exec, omarchy-hyprland-window-pop
# bindd = $mainMod, L, Toggle workspace layout, exec, omarchy-hyprland-workspace-layout-toggle

# Toggle between Scroll and Dwindle layout
unbind = $mainMod ALT SHIFT CTRL, M
bind = $mainMod ALT SHIFT CTRL, M, exec, omarchy-hyprland-workspace-layout-toggle