# Workspace navigation

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Switch to previous/next workspace with mainMod + Alt + H/L
unbind = $mainMod ALT, H
unbind = $mainMod ALT, L
bind = $mainMod ALT, H, workspace, e-1
bind = $mainMod ALT, L, workspace, e+1

# Switch to previous/next workspace with mainMod + Alt + arrows
unbind = $mainMod ALT, left
unbind = $mainMod ALT, right
bind = $mainMod ALT, left, workspace, e-1
bind = $mainMod ALT, right, workspace, e+1

# TAB between workspaces
bindd = $mainMod, TAB, Next workspace, workspace, e+1
bindd = $mainMod SHIFT, TAB, Previous workspace, workspace, e-1
bindd = $mainMod CTRL, TAB, Former workspace, workspace, previous

# Move workspaces to other monitors
bindd = $mainMod CTRL ALT, LEFT, Move workspace to left monitor, movecurrentworkspacetomonitor, l
bindd = $mainMod CTRL ALT, RIGHT, Move workspace to right monitor, movecurrentworkspacetomonitor, r
bindd = $mainMod CTRL ALT, UP, Move workspace to up monitor, movecurrentworkspacetomonitor, u
bindd = $mainMod CTRL ALT, DOWN, Move workspace to down monitor, movecurrentworkspacetomonitor, d