# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Source categorized bindings
source = ~/.config/hypr/bindings/apps.conf
source = ~/.config/hypr/bindings/window-nav.conf
source = ~/.config/hypr/bindings/workspace.conf
source = ~/.config/hypr/bindings/window-mgmt.conf
source = ~/.config/hypr/bindings/system.conf
source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/groups.conf
