

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


# Unreal Editor window behavior
windowrule = no_initial_focus on, match:class ^UnrealEditor$
windowrule = no_anim on, match:class ^UnrealEditor$
windowrule = focus_on_activate off, match:class ^UnrealEditor$


# layerrule = pin on, match:namespace neru
# layerrule = opacity 1.0 override, match:namespace neru
# layerrule = order 100, match:namespace neru

