

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


# Unreal Editor window behavior
windowrule{
  name = unreal-editor-window-rules
  match:class = ^UnrealEditor$

  no_initial_focus = on 
  no_anim = on 
  focus_on_activate = off
}
# layerrule = pin on, match:namespace neru
# layerrule = opacity 1.0 override, match:namespace neru
# layerrule = order 100, match:namespace neru

